Add clear error message when kubeconfig is missing for `operator-sdk scorecard`
Executing `operator-sdk scorecard` without kubeconfig fails with
following error:

BEFORE:
```
$ operator-sdk scorecard --cr-manifest deploy/crds/app_v1alpha1_appservice_cr.yaml --olm-tests=false
Error: invalid configuration: no configuration has been provided
```

It is difficult to realize what config file was invalid by reading
`Error: invalid configuration: no configuration has been provided`.

This patch adds clear message when kubeconfig is missing or failed to
parse.

AFTER:
```
$ operator-sdk scorecard --cr-manifest deploy/crds/cache_v1alpha1_memcached_cr.yaml --olm-tests=false
Error: failed to build the kubeconfig: invalid configuration: no configuration has been provided
```