Pin to ansible 2.9 (#3935)
* Unpin molecule

molecule was probably pinned due to a dependency issue, but has since
been bumped by a major version.

* Restrict ansible to < 2.10

Molecule was unable to import something

File "/home/travis/.local/lib/python3.6/site-packages/molecule/driver/docker.py", line 222, in sanity_checks
   from ansible.module_utils.docker.common import HAS_DOCKER_PY
ModuleNotFoundError: No module named 'ansible.module_utils.docker'